const productos = [
    {
        id: 1,
        materiales: "Madera",
        medidas: "Xcm x Xcm",
        precios: 123,
        imagen: "img/productos/bandejas.jpeg",
        category: "Madera"
    },
    {
        id: 2,
        materiales: "Madera",
        medidas: "Xcm x Xcm",
        precios: 231,
        imagen: "img/productos/bolsa-nevideña.jpeg",
        category: "Todo Tela"
    },
    {
        id: 3,
        category: "Pañolenci",
        materiales: "Madera",
        medidas: "Xcm x Xcm",
        precios: 312,
        imagen: "img/productos/caramelera-chica.jpeg",
    },
    {
        id: 4,
        category: "Madera",
        materiales: "Madera",
        medidas: "Xcm x Xcm",
        precios: 321,
        imagen: "img/productos/caramelera-grande.jpeg",
    },
    {
        id: 5,
        category: "Madera",
        materiales: "Madera",
        medidas: "Xcm x Xcm",
        precios: 321,
        imagen: "img/productos/cara-papa-noel.jpeg",
    },
    {
        id: 6,
        category: "Madera",
        materiales: "Madera",
        medidas: "Xcm x Xcm",
        precios: 321,
        imagen: "img/productos/cartel-puerta-chico (1).jpeg",
    },
    {
        id: 7,
        category: "Madera",
        materiales: "Madera",
        medidas: "Xcm x Xcm",
        precios: 321,
        imagen: "img/productos/cartel-picaporte.jpeg",
    },
    {
        id: 8,
        category: "Madera",
        materiales: "Madera",
        medidas: "Xcm x Xcm",
        precios: 321,
        imagen: "img/productos/cartel-puerta-grande (1).jpeg",
    },
    {
        id: 9,
        category: "Madera",
        materiales: "Madera",
        medidas: "Xcm x Xcm",
        precios: 321,
        imagen: "img/productos/cartel-maceta-1.jpeg",
    },
    {
        id: 10,
        category: "Madera",
        materiales: "Madera",
        medidas: "Xcm x Xcm",
        precios: 321,
        imagen: "img/productos/centro-de-mesa.jpeg",
    },
    {
        id: 11,
        category: "Madera",
        materiales: "Madera",
        medidas: "Xcm x Xcm",
        precios: 321,
        imagen: "img/productos/cono-papa-noel.jpeg",
    },
    {
        id: 12,
        category: "Madera",
        materiales: "Madera",
        medidas: "Xcm x Xcm",
        precios: 321,
        imagen: "img/productos/cubre-botella.jpeg",
    },
    {
        id: 13,
        category: "Madera",
        materiales: "Madera",
        medidas: "Xcm x Xcm",
        precios: 321,
        imagen: "img/productos/cubre-tapas.jpeg",
    },
    {
        id: 14,
        category: "Madera",
        materiales: "Madera",
        medidas: "Xcm x Xcm",
        precios: 321,
        imagen: "img/productos/duende-xmas.jpeg",
    },
    {
        id: 15,
        category: "Madera",
        materiales: "Madera",
        medidas: "Xcm x Xcm",
        precios: 321,
        imagen: "img/productos/figura-para-colgar.jpeg",
    },
    {
        id: 16,
        category: "Madera",
        materiales: "Madera",
        medidas: "Xcm x Xcm",
        precios: 321,
        imagen: "img/productos/figuras-para-parar (1).jpeg",
    },
    {
        id: 17,
        category: "Madera",
        materiales: "Madera",
        medidas: "Xcm x Xcm",
        precios: 321,
        imagen: "img/productos/maceteros.jpeg",
    },
    {
        id: 18,
        category: "Madera",
        materiales: "Madera",
        medidas: "Xcm x Xcm",
        precios: 321,
        imagen: "img/productos/juegos-3-papa-noel.jpeg",
    },
    {
        id: 19,
        category: "Madera",
        materiales: "Madera",
        medidas: "Xcm x Xcm",
        precios: 321,
        imagen: "img/productos/manopla-grande.jpeg",
    },
    {
        id: 20,
        category: "Madera",
        materiales: "Madera",
        medidas: "Xcm x Xcm",
        precios: 321,
        imagen: "img/productos/papa-noel-mediano.jpeg",
    },
    {
        id: 21,
        category: "Madera",
        materiales: "Madera",
        medidas: "Xcm x Xcm",
        precios: 321,
        imagen: "img/productos/papa-noel-patas-larga.jpeg",
    },
    {
        id: 22,
        category: "Madera",
        materiales: "Madera",
        medidas: "Xcm x Xcm",
        precios: 321,
        imagen: "img/productos/papa-noel-rojo-verde.jpeg",
    },
    {
        id: 23,
        category: "Madera",
        materiales: "Madera",
        medidas: "Xcm x Xcm",
        precios: 321,
        imagen: "img/productos/papa-noel-sentado.jpeg",
    }
]

module.exports = productos;
